// client/src/App.vue
<template>
  <div id="app">
    <h2>{{ extension.name }}</h2>
    <div class="tricks">
      <div class="color" v-for="color in colors" :key="color.name">
        <div>{{ color.name }}</div>
        <Card v-for="(card, index) in color.cards" :key="index" :card="card" />
      </div>
    </div>
  </div>
</template>

<script>
import extension from '@/tricks/znr.json'
import Card from '@/components/Card'

const costRegexp = new RegExp(/\{([G, W, B, U, R, \d, X, \/]+)\}/g)

export default {
  name: 'App',
  components: { Card },
  data() {
    return { extension }
  },
  computed: {
    cards() {
      return this.extension.cards.map(c => {
        const costs = []
        let cost = costRegexp.exec(c.mana_cost)
        while (cost !== null) {
          const className = `ms-${cost[1]
            .split('/')
            .join('')
            .toLowerCase()}`
          costs.push(`${className} ms ms-cost`)
          cost = costRegexp.exec(c.mana_cost)
        }
        return { ...c, costs }
      })
    },
    colors() {
      const colors = {
        W: { cards: [], name: 'W', className: 'white' },
        U: { cards: [], name: 'U', className: 'blue' },
        B: { cards: [], name: 'B', className: 'black' },
        R: { cards: [], name: 'R', className: 'red' },
        G: { cards: [], name: 'G', className: 'green' },
        multi: { cards: [], name: 'Multi', className: 'multicolore' },
        colorless: { cards: [], name: 'Colorless', className: 'multicolore' },
      }
      this.cards.forEach(card => {
        const cardColors = card.colors
        if (cardColors.length > 1) {
          colors.multi.cards.push(card)
          return
        }
        if (cardColors.length === 0) {
          colors.colorless.cards.push(card)
          return
        }
        colors[cardColors[0]].cards.push(card)
      })

      Object.keys(colors).forEach(key => {
        if (colors[key].cards.length === 0) {
          delete colors[key]
        } else {
          colors[key].cards.sort((a, b) => a.cmc - b.cmc)
        }
      })

      return colors
    },
  },
}
</script>

<style>
.tricks {
  display: flex;
}
.color {
  flex: 1;
}
</style>

// src/app/app.component.ts
import { Component } from '@angular/core';
import * as _ from "lodash";

import { Card, tricks } from "../data/AKH-tricks"


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  dashboardLink: string = "http://mtg-stats.purple-fox.fr/app/kibana#/dashboard/0f1b4b30-2204-11e7-a4a7-a3aa983ebfc9";
  data: any[] = [];

  constructor() {
    const costRegexp = new RegExp(/\{(.)\}/g);
    const cards = tricks.map(c => {
      const costs = [];
      let cost = costRegexp.exec(c.manaCost);
      while(cost !== null) {
        costs.push(`ms-${cost[1].toLowerCase()} ms ms-cost`);
        cost = costRegexp.exec(c.manaCost);
      }
      return {
        name: c.name,
        cmc: c.cmc,
        manaCost: c.manaCost,
        colors: c.colors,
        effect: c.effect,
        costs
      };
    });

    const costs = _.groupBy(cards, "cmc");
    Object.keys(costs).forEach(cmc => {
      this.data.push({
        cmc,
        colors: _.groupBy(costs[cmc], (card: Card) => {
          const colors: string[] = card.colors.split(",");
          if (colors.length > 1) return "Multicolore";
          else return card.colors;
        })
      })
    });
    console.log("data", this.data);
    this.data.forEach(d => {
      d.max = _.range(Math.max(
        (d.colors.White || []).length,
        (d.colors.Black || []).length,
        (d.colors.Green || []).length,
        (d.colors.Blue || []).length,
        (d.colors.Multicolore || []).length,
        (d.colors.Red || []).length
      ));
    })
  }
}

<h1>All instants, flash creatures and cycling with effects in AKH</h1>
<table class="cards">
  <thead>
    <tr>
      <th>CCM</th>
      <th colspan="2" class="white">White</th>
      <th colspan="2" class="blue">Blue</th>
      <th colspan="2" class="black">Black</th>
      <th colspan="2" class="red">Red</th>
      <th colspan="2" class="green">Green</th>
      <th colspan="2" class="multi">Multi</th>
    </tr>
  </thead>
  <tbody>
    <ng-template ngFor [ngForOf]="data" let-d>
      <tr>
        <td [attr.rowspan]="d.max.length + 1" class="cmc">{{d.cmc}}</td>
      </tr>
      <tr *ngFor="let i of d.max;let l = last" [class.border-top]="i === 0" [class.last]="l">
        <td class="cost">
          <span *ngIf="d.colors.White && d.colors.White[i]">
              <i *ngFor="let cost of d.colors.White[i].costs" [ngClass]="cost"></i>
          </span>
        </td>
        <td class="white name">
            <card [card]="d.colors.White[i]" *ngIf="d.colors.White && d.colors.White[i]"></card>
            <br/><i *ngIf="d.colors.White && d.colors.White[i] && d.colors.White[i].effect">({{d.colors.White[i].effect}})</i>
        </td>
        <td class="cost">
          <span *ngIf="d.colors.Blue && d.colors.Blue[i]">
            <i *ngFor="let cost of d.colors.Blue[i].costs" [ngClass]="cost"></i>
          </span>
        </td>
        <td class="blue name">
          <card [card]="d.colors.Blue[i]" *ngIf="d.colors.Blue && d.colors.Blue[i]"></card>
          <br><i *ngIf="d.colors.Blue && d.colors.Blue[i] && d.colors.Blue[i].effect">({{d.colors.Blue[i].effect}})</i>
        </td>
        <td class="cost">
           <span *ngIf="d.colors.Black && d.colors.Black[i]">
              <i *ngFor="let cost of d.colors.Black[i].costs" [ngClass]="cost"></i>
            </span>
        </td>
        <td class="black name">
          <card [card]="d.colors.Black[i]" *ngIf="d.colors.Black && d.colors.Black[i]"></card>
          <br><i *ngIf="d.colors.Black && d.colors.Black[i] && d.colors.Black[i].effect">({{d.colors.Black[i].effect}})</i>
        </td>
        <td class="cost">
          <span *ngIf="d.colors.Red && d.colors.Red[i]">
              <i *ngFor="let cost of d.colors.Red[i].costs" [ngClass]="cost"></i>
            </span>
        </td>
        <td class="red name">
          <card [card]="d.colors.Red[i]" *ngIf="d.colors.Red && d.colors.Red[i]"></card>
          <br><i *ngIf="d.colors.Red && d.colors.Red[i] && d.colors.Red[i].effect">({{d.colors.Red[i].effect}})</i>
        </td>
        <td class="cost">
          <span *ngIf="d.colors.Green && d.colors.Green[i]">
              <i *ngFor="let cost of d.colors.Green[i].costs" [ngClass]="cost"></i>
            </span>
        </td>
        <td class="green name">
          <card [card]="d.colors.Green[i]" *ngIf="d.colors.Green && d.colors.Green[i]"></card>
          <br><i *ngIf="d.colors.Green && d.colors.Green[i] && d.colors.Green[i].effect">({{d.colors.Green[i].effect}})</i>
        </td>
        <td class="cost">
          <span *ngIf="d.colors.Multicolore && d.colors.Multicolore[i]">
              <i *ngFor="let cost of d.colors.Multicolore[i].costs" [ngClass]="cost"></i>
            </span>
        </td>
        <td class="multi name">
          <card [card]="d.colors.Multicolore[i]" *ngIf="d.colors.Multicolore && d.colors.Multicolore[i]"></card>
          <br><i *ngIf="d.colors.Multicolore && d.colors.Multicolore[i] && d.colors.Multicolore[i].effect">({{d.colors.Multicolore[i].effect}})</i>
        </td>
      </tr>
    </ng-template>
  </tbody>
</table>
<a [href]="dashboardLink">Link to stats</a>
